name: Generate string + matrix

on:
  workflow_call:
    inputs:
      input-string:
        description: "String to generate"
        required: false
        type: string
        default: "default-string"
      max:
        description: "How many matrix entries"
        required: false
        type: number
        default: 10
    outputs:
      generated:
        description: "The generated string"
        value: ${{ jobs.generate-string.outputs.my_string }}

jobs:
  generate-string:
    runs-on: ubuntu-latest
    outputs:
      my_string: ${{ steps.generate.outputs.result }}
    steps:
      - name: Use composite action
        id: generate
        uses: abreiss/LEB-C2-EX2-COMP-GEN-STRING-@62fe3369a18437665f03d1051ee811f1e263f6a7
        with:
          input-string: ${{ inputs.input-string }}

  matrix-job:
    needs: generate-string
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1,2,3,4,5,6,7,8,9,10]  # (see note below)
    steps:
      - name: Print output with number
        run: echo "${{ needs.generate-string.outputs.my_string }}-${{ matrix.number }}"
